# Generated by Django 4.2 on 2025-01-13 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('main_image', models.FileField(blank=True, max_length=256, null=True, upload_to='save_profile_image/')),
                ('role', models.ForeignKey(default=user_management.models.Role.get_default_role, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='user_management.role')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
